- name: Install the latest version of nginx
  yum:
    name: nginx
    state: latest

- name: Remove oldhtdocs file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Extract Packages
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy Extract directory
  ansible.builtin.copy:
    src: /usr/share/nginx/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Start Nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes


