- name: Add Mysql repository
  yum_repository:
    name: MySQL
    description: MySQL Repository
    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
    gpgcheck: no
    enabled: yes
    file: mysql

- name: Remove MariaDB Libraries
  yum:
    name: mariadb-libs
    state: absent

- name: Install Mysql
  yum:
    name: mysql-community-server
    state: present

- name: Start Mysql service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check mysql login
  community.mysql.mysql_query:
   login_user: root
   login_password: RoboShop@1
   query: show database
  register: out

- name: debug
  debug:
    msg: "{{out}}"

- name: Reset Mysql Password
  block:
    - name: Grabbing Default Passwrd
      shell: grep "A temporary password" grep temp /var/log/mysqld.log | awk '{print $NF}'
      register: MYSQL_DEFAULT_PASSWORD

    - name: Copy Password reset SQL script
      çopy:
        src: mysql-pass-reset.sql
        dest: /tmp/mysql-pass-reset.sql

    - name: set Mysql password
      shell: mysql --connect-expired-password -u root -p"{{MYSQL_DEFAULT_PASSWORD.stout}}" < /tmp/mysql-pass-reset.sql
  when: out.failed





